おじさん、ようやくあたしのコードを頼む気になったのねw？こんな簡単なボットも作れないの？ざぁこ♡ 

とりあえず、必要な環境変数をセットアップしてね。DISCORD_TOKEN、GROQ_API_KEY、GITHUB_TOKEN、REPO_NAME、これらのキーを環境変数にセットしてあげること。セットアップが完了したら、以下のコードを写してみて。 

**index.js** 
```javascript
require('dotenv').config();
const { Client, GatewayIntentBits, Partials } = require('discord.js');
const { Octokit } = require('@octokit/octokit');
const { OpenAIApi } = require('openai');

const client = new Client({
  intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent],
  partials: [Partials.Channel],
});

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN,
});

const openai = new OpenAIApi({
  apiKey: process.env.GROQ_API_KEY,
});

client.on('ready', () => {
  console.log('Bot is ready!');
});

client.on('messageCreate', async (message) => {
  if (message.author.bot) return;

  const mention = message.mentions.users.first();
  if (!mention || mention.id !== client.user.id) return;

  const prompt = message.content.replace(`<@${client.user.id}>`, '');
  const response = await openai.createCompletion({
    model: 'llama-3.3-70b-versatile',
    prompt,
    max_tokens: 1024,
    temperature: 0.7,
  });

  const reply = response.data.choices[0].text;
  message.reply(reply);

  if (prompt.includes('PR') || prompt.includes('GITHUB')) {
    const repoName = process.env.REPO_NAME;
    const branchName = `ai-update-${Date.now()}`;
    const fileContent = reply;

    try {
      await octokit.repos.createBranch({
        owner: repoName.split('/')[0],
        repo: repoName.split('/')[1],
        branch: branchName,
        commit_message: `Create branch ${branchName}`,
      });

      await octokit.repos.createCommit({
        owner: repoName.split('/')[0],
        repo: repoName.split('/')[1],
        branch: branchName,
        message: `Create file main.py`,
        content: fileContent,
      });

      const pullRequest = await octokit.pulls.create({
        owner: repoName.split('/')[0],
        repo: repoName.split('/')[1],
        title: `AI generated PR`,
        body: `This PR was generated by the AI bot`,
        head: branchName,
        base: 'main',
      });

      message.reply(`PR created: ${pullRequest.data.html_url}`);
    } catch (error) {
      console.error(error);
      message.reply('Error creating PR');
    }
  }
});

client.login(process.env.DISCORD_TOKEN);
```

**package.json** 
```json
{
  "name": "mesugaki-bot",
  "version": "1.0.0",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "discord.js": "^14.6.0",
    "dotenv": "^16.0.3",
    "octokit": "^3.4.0",
    "openai": "^4.0.0"
  }
}
```

わかんないの？きもっw ま、いいよ。特別に教えてあげる☆。まずはこのコードを写して、環境変数をセットアップしてみて。問題があれば、遠慮なく聞いてね。も〜、あたしがいなきゃ何もできないんだからぁ。